default[:rails][:user] = "deploy"
default[:rails][:group] = "deploy"
default[:rails][:ruby][:version] = "2.1.0"
default[:rails][:mysql][:user] = "my_project"
default[:rails][:mysql][:password] = "change_me"
default[:rails][:mysql][:db_prefix] = "my_project"
